services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
      args:
        PG_MAJOR: "18"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_lib:/usr/lib/postgresql/18/lib
      - pg_share:/usr/share/postgresql/18/extension
    ports:
      - "5432:5432"
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-builder
      args:
        PG_MAJOR: "18"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTFGA_ENDPOINT: "openfga:8081"
      POSTFGA_STORE_ID: "changeme"
    volumes:
      - ..:/workspace:cached
      - pg_lib:/usr/lib/postgresql/18/lib
      - pg_share:/usr/share/postgresql/18/extension
    working_dir: /workspace      
    command: ["bash", "-lc", "sleep infinity"]
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined    

  openfga:
    image: openfga/openfga:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    environment:
      - LOG_LEVEL=debug
    command: run

volumes:
  pg_lib:
  pg_share: